webtalk_init -webtalk_dir Z:/Universidad/Vivado/SED_Trabajo_VHDL/SED_Trabajo_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SEMAFORO_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 12 21:22:18 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ac0bb0b-b93e-43fa-bf8e-f951911346bf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "27cd5abe883f43439bb77359fe1d4cba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3504 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7176_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2725561261 -regid "" -xml Z:/Universidad/Vivado/SED_Trabajo_VHDL/SED_Trabajo_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SEMAFORO_behav/webtalk/usage_statistics_ext_xsim.xml -html Z:/Universidad/Vivado/SED_Trabajo_VHDL/SED_Trabajo_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SEMAFORO_behav/webtalk/usage_statistics_ext_xsim.html -wdm Z:/Universidad/Vivado/SED_Trabajo_VHDL/SED_Trabajo_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SEMAFORO_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
